#!/usr/bin/env python3
"""
Standalone script to visualize building instances from CLIPSeg's output.

This script reads the probability maps generated by a segmentation model,
identifies individual object instances (e.g., buildings), and generates
a 3-panel comparison image:
1. Original Image
2. CLIPSeg's raw binary mask
3. Instance segmentation with unique colors for each building
"""

import os
import sys
from pathlib import Path
import cv2
import numpy as np
from PIL import Image
from tqdm import tqdm
import matplotlib.pyplot as plt

# Ensure the project root is in the Python path
sys.path.append(str(Path(__file__).parent.parent.parent))

def create_instance_overlay(
    original_image: np.ndarray,
    prob_map: np.ndarray,
    prob_threshold: float,
    min_area: int
) -> tuple[np.ndarray, int]:
    """
    Finds, filters, and creates an overlay of colored object instances.

    Args:
        original_image: The original satellite image as a numpy array.
        prob_map: The probability map from the segmentation model.
        prob_threshold: The threshold to create a binary mask.
        min_area: The minimum area in pixels for an instance to be kept.

    Returns:
        A tuple containing:
        - A visualization image with instances highlighted.
        - The number of instances found.
    """
    # 1. Threshold the probability map to get a binary mask
    binary_mask = (prob_map > prob_threshold).astype(np.uint8) * 255

    # 2. Find all distinct contours (potential instances)
    contours, _ = cv2.findContours(
        binary_mask,
        cv2.RETR_EXTERNAL,
        cv2.CHAIN_APPROX_SIMPLE
    )

    # 3. Filter contours by area to remove noise
    filtered_contours = [
        c for c in contours if cv2.contourArea(c) > min_area
    ]

    # 4. Prepare for visualization
    # Create a blended image for drawing to make instance colors pop
    viz_image = cv2.addWeighted(original_image, 0.7, np.zeros_like(original_image), 0.3, 0)

    # 5. Draw each filtered contour (instance) with a unique color
    for i, contour in enumerate(filtered_contours):
        color = plt.cm.get_cmap('gist_rainbow', len(filtered_contours))(i)[:3]
        color = [int(c * 255) for c in color]

        cv2.drawContours(viz_image, [contour], -1, color, -1)
        x, y, w, h = cv2.boundingRect(contour)
        cv2.rectangle(viz_image, (x, y), (x + w, y + h), color, 1)
        label = f"B_{i+1}"
        cv2.putText(
            viz_image, label, (x, y - 5),
            cv2.FONT_HERSHEY_SIMPLEX, 0.4, color, 1
        )

    return viz_image, len(filtered_contours)

def save_comparison_figure(
    original_img: np.ndarray,
    clipseg_mask_img: np.ndarray,
    instance_img: np.ndarray,
    save_path: Path,
    num_instances: int
):
    """
    Saves a 3-panel comparison figure.
    """
    fig, axes = plt.subplots(1, 3, figsize=(18, 6))
    plt.suptitle(f"Instance Segmentation Result for {save_path.stem}", fontsize=16)

    axes[0].imshow(original_img)
    axes[0].set_title('Original Image')
    axes[0].axis('off')

    axes[1].imshow(clipseg_mask_img)
    axes[1].set_title('CLIPSeg Output Mask')
    axes[1].axis('off')

    axes[2].imshow(instance_img)
    axes[2].set_title(f'Instance Segmentation ({num_instances} found)')
    axes[2].axis('off')

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.close(fig)

def main():
    """Main function to run the instance visualization process."""
    # --- Configuration ---
    CLIPSEG_PROB_DIR = "output/inference/finetuned/probabilities"
    TEST_IMAGES_DIR = "data/Vaihingen/finetune_data/test/images"
    OUTPUT_DIR = "output/instance_visualization"
    CLASS_TO_PROCESS = 'building'
    PROB_THRESHOLD = 0.5
    MIN_AREA = 50
    BUILDING_COLOR = [0, 0, 255] # Blue for buildings in CLIPSeg mask

    # --- Setup ---
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    test_images = sorted(Path(TEST_IMAGES_DIR).glob("*.tif"))
    print(f"Starting instance visualization for class: '{CLASS_TO_PROCESS}'")

    # --- Processing Loop ---
    for img_path in tqdm(test_images, desc="Visualizing Instances"):
        img_name = img_path.stem
        prob_map_path = Path(CLIPSEG_PROB_DIR) / f"{img_name}_{CLASS_TO_PROCESS}_prob.npy"

        if not prob_map_path.exists():
            continue

        # Load original image and probability map
        original_image = np.array(Image.open(img_path).convert("RGB"))
        prob_map = np.load(prob_map_path)

        # --- Create the 3 panels ---

        # Panel 1: Original Image (already loaded)

        # Panel 2: CLIPSeg's raw output mask
        clipseg_binary_mask = (prob_map > PROB_THRESHOLD).astype(np.uint8)
        clipseg_viz_mask = np.zeros_like(original_image)
        clipseg_viz_mask[clipseg_binary_mask == 1] = BUILDING_COLOR

        # Panel 3: Instance Segmentation Overlay
        instance_overlay, num_found = create_instance_overlay(
            original_image=original_image,
            prob_map=prob_map,
            prob_threshold=PROB_THRESHOLD,
            min_area=MIN_AREA
        )

        # --- Save the final figure ---
        output_path = Path(OUTPUT_DIR) / f"{img_name}_instances_comparison.png"
        save_comparison_figure(
            original_img=original_image,
            clipseg_mask_img=clipseg_viz_mask,
            instance_img=instance_overlay,
            save_path=output_path,
            num_instances=num_found
        )

    print(f"\n✓ Instance visualization complete.")
    print(f"  Results saved to: {OUTPUT_DIR}")

if __name__ == "__main__":
    main()